include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_classes_with_only_static_members: false
    type_annotate_public_apis: false
    annotate_overrides: true
    omit_local_variable_types: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    use_super_parameters: false

analyzer:
  errors:
    missing_required_param: error
  strong-mode:
    implicit-casts: false
  exclude:
    - lib/**.i18n.dart
    - lib/**.chopper.dart
    - lib/**.g.dart
    - example/**