platform :ios, '11.3'
inhibit_all_warnings!
use_frameworks!

project ''

target 'flutter_phone_lib' do
  source 'https://gitlab.linphone.org/BC/public/podspec.git'
  source 'https://github.com/CocoaPods/Specs.git'

  pod 'iOSVoIPLib', :git => 'https://github.com/open-voip-alliance/iOS-VoIP-Lib.git'
  pod 'PIL', :git => 'https://github.com/open-voip-alliance/iOS-Phone-Integration-Lib.git'

end
