platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!

project ''

target 'flutter_phone_lib' do
  source 'https://gitlab.linphone.org/BC/public/podspec.git'
  source 'https://github.com/CocoaPods/Specs.git'

  pod 'iOSPhoneLib', :git =>'https://github.com/open-voip-alliance/iOS-Phone-Lib.git'

end
